import mongoose, { Schema, Document } from 'mongoose';

export interface IInstructor extends Document {
  instructorId: string;
  firstName: string;
  lastName: string;
  address: string;
  phone: string;
  email: string;
  preferredContact: 'phone' | 'email';
  createdAt: Date;
}

/** A studio instructor. The readable instructorId (I00001) is generated by the service, not sent by the client. */
const instructorSchema = new Schema<IInstructor>(
  {
    instructorId: {
      type: String,
      required: true,
    },
    firstName: {
      type: String,
      required: [true, 'First name is required'],
      trim: true,
    },
    lastName: {
      type: String,
      required: [true, 'Last name is required'],
      trim: true,
    },
    address: {
      type: String,
      trim: true,
      default: '',
    },
    phone: {
      type: String,
      trim: true,
      default: '',
    },
    email: {
      type: String,
      trim: true,
      lowercase: true,
      default: '',
    },
    preferredContact: {
      type: String,
      enum: ['phone', 'email'],
      default: 'email',
    },
  },
  {
    timestamps: true,
  }
);

// No two instructors share an ID
instructorSchema.index({ instructorId: 1 }, { unique: true });

export const Instructor = mongoose.model<IInstructor>('Instructor', instructorSchema);
